plugins {
    id 'java'
}

group = 'cz.yourname.esgsearch'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://repo.codemc.io/repository/maven-public/' }
    maven { url = 'https://jitpack.io' }
}

dependencies {
    // Paper API pro nejnovější verzi Minecraftu (1.21+)
    compileOnly 'io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT'
    
    // EconomyShopGUI API z JitPacku
    compileOnly 'com.github.Gypopo:EconomyShopGUI-API:1.7.1'
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
