discord-webhook:
  enabled: false
  url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL_HERE"
  buy-message: "**{player}** si koupil **{amount}x {item}** za **${price}**!"
  sell-message: "**{player}** prodal **{amount}x {item}** a vydělal **${price}**!"

gui:
  title: "&8Aukce / Obchod"
  back-button: "&cZpět do obchodu"
  buy-button:
    name: "&a&lKOUPIT ({amount}x)"
    lore:
      - "&7Klikni pro nákup za &a${price}"
  sell-button:
    name: "&c&lPRODAT ({amount}x)"
    lore:
      - "&7Klikni pro prodej za &a${price}"
  center-item:
    lore-selected: "&7Vybrané množství: &e{amount}"
    lore-buy-price: "&aCena za nákup: &f${price}"
    lore-sell-price: "&cCena za prodej: &f${price}"
    lore-cannot-sell: "&cTento předmět nelze prodat."

messages:
  prefix: "&8[&eESGSearch&8] "
  usage: "&cPoužití: /search <název položky|reload>"
  only-player: "&cTento příkaz může použít pouze hráč!"
  not-found: "&cPoložka '&e{input}&c' nebyla v konfiguraci nalezena!"
  not-in-shop: "&cPoložka '&e{item}&c' se nenachází v obchodě!"
  buy-success: "&aÚspěšně jsi koupil {amount}x {item} za ${price}"
  sell-success: "&aÚspěšně jsi prodal {amount}x {item} za ${price}"
  no-money: "&cNemáš dostatek peněz na tento nákup!"
  no-items: "&cNemáš v inventáři dostatek těchto předmětů k prodeji!"
  cannot-sell: "&cTento předmět nelze prodat."

items:
  GRASS_BLOCK:
    formats: "Grass Block,grassblock,grass_block,grass block"
  DIRT:
    formats: "Dirt,dirt"
